x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ~/.miniUnicorn:/home/miniUnicorn/.miniUnicorn
  cap_drop:
    - ALL
  cap_add:
    - SYS_ADMIN
  security_opt:
    - apparmor=unconfined
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 1G
        pids: 200
      reservations:
        cpus: "0.25"
        memory: 256M

services:
  miniUnicorn-gateway:
    container_name: miniUnicorn-gateway
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 8765:8765

  miniUnicorn-api:
    container_name: miniUnicorn-api
    <<: *common-config
    command:
      ["serve", "--host", "0.0.0.0", "-w", "/home/miniUnicorn/.miniUnicorn/api-workspace"]
    restart: unless-stopped
    ports:
      - 127.0.0.1:8900:8900

  miniUnicorn-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
